### ISSUE TITLE
Relative paths for textures.

### ISSUE THREAD

**Issue by tsharju** [dmsurti/AssimpKit#53] opened 2017-06-20 13:34 UTC
Seems that it does not matter if I put a relative path for textures and I load the `SCNScene` using `AssimpKit`, the texture always has a absolute path. I'm using `AssimpKit` for importing our models in FBX format and then save the `SCNScene` to `.scn` files. Problem is that now all textures have absolute paths since `AssimpImporter` seems to take the texture path from the scene file path. Would it be possible to add support for using only the path set in the model and not change it at all?

**Comment by dmsurti** [comment] 2017-06-25 17:59
@tsharju Thanks for reporting this.

>> Would it be possible to add support for using only the path set in the model and not change it at all?

This is definitely a bug, even `Assimp` does not change the path set in the model. IIRC, I was `inspired` by Blender export settings to have both relative and full file paths for textures. And the fact that tests passed for my initial app which motivated this library, I think I left it at that!

It will be great if you can share a sample file, which does not load the textures due to the above bug, will help in updating the regression test library.

Self note:
Culprit:
https://github.com/dmsurti/AssimpKit/blob/master/AssimpKit/Code/Model/AssimpImporter.m#L595

**Comment by tsharju** [comment] 2017-06-26 05:30
I suppose my problem is mostly that I'm using AssimpKit in MacOS and importing an `.fbx` file, that I then export to `.scn` using AssimpKit. I think the problem is [here](https://github.com/dmsurti/AssimpKit/blob/master/AssimpKit/Code/Model/AssimpImporter.m#L600). The `sceneDir` is essentially the path from where the assets were loaded. Now if I save this to `.scn` file and load it to an iOS project, it will have texture path that points to a directory on my MacOS. This obviously won't happen if you only use AssimpKit on iOS. So only when you export `.scn` file on MacOS and then load it on iOS. If you can try that. Basically any asset will fail in this case.

Oh, and thanks for a great library. Really useful and helps a lot when working with SceneKit. :)

**Comment by dmsurti** [comment] 2017-06-27 06:48
>>  and load it to an iOS project, it will have texture path that points to a directory on my MacOS.

Ahh, my original app did not have this use case. Thanks for the details, this helps a lot in updating the test suite.

>> Oh, and thanks for a great library. Really useful and helps a lot when working with SceneKit. :)

Pleased to know that you find this library useful. 👍

**Comment by dmsurti** [comment] 2017-09-02 09:12
@tsharju I have modified the design in #64, so that color/image objects are applied instead of relying on any external resource. I have tested this by exporting a model to scene kit archive on macOS and testing the exported archive in a scene kit app in an iOS device and that works fine. 

Thanks for collaborating, closing this.

**Closed by dmsurti** 2017-09-02 09:12 UTC
Labels: bug

**Comment by tsharju** [comment] 2017-09-02 09:28
Thanks. Will try it out. :)

**Comment by MadhuiOS** [comment] 2018-02-05 11:32
Hello @dmsurti,
first  thanks for a great library. i am using it to load FBX files in my iOS application, but it is not loading textures, can you please help me this.

**Comment by dmsurti** [comment] 2018-02-06 10:35
@MadhuiOS 

>> first thanks for a great library

👍 

>>  i am using it to load FBX files in my iOS application, but it is not loading textures, can you please help me this.

Kindly request you to open a new issue and attach a sample asset to reproduce the problem with any logs reported, that can help to resolve the issue you are facing.
